name: Deploy my-other-app

on:
  push:
    branches:
      - main
      - production-my-other-app
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build app
        run: |
          cd packages/my-other-app
          pnpm run build
      - name: Publish
        id: cloudflare
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cf-switch-test
          directory: packages/my-other-app/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref || github.ref_name }}
      - name: Get Deployment Alias
        if: github.event_name == 'pull_request'
        id: get-alias
        run: |
          deployment_response=$(curl --request GET --url https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/cf-switch-test/deployments/${{ steps.cloudflare.outputs.id }} --header 'Content-Type: application/json' -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}")
          alias=$(jq -r '.result.aliases[0]' <<< "$deployment_response")
          echo "alias=$alias" >> "$GITHUB_OUTPUT"
      - name: Echo outputs
        run: |
          echo ${{ github.event_name }}
          echo ${{ steps.cloudflare.outputs.id }}
          echo ${{ steps.cloudflare.outputs.url }}
          echo ${{ steps.cloudflare.outputs.environment }}
          echo ${{ steps.get-alias.outputs.alias }}
      - name: Add deployment PR comment
        uses: mshick/add-pr-comment@v2
        if: github.event_name == 'pull_request'
        with:
          message-id: cloudflare-deploy-2
          message: |
            ### <img alt="" src="https://user-images.githubusercontent.com/23264/106598434-9e719e00-654f-11eb-9e59-6167043cfa01.png" width="16"> &nbsp;Cloudflare Pages
  
            <table>
            <tr><td><strong>App:</strong></td><td>My Other App</td></tr>
            <tr>
            <td><strong>Branch Preview URL:</strong></td>
            <td><a href='${{ steps.get-alias.outputs.alias }}'>${{ steps.get-alias.outputs.alias }}</a></td>
            </tr>
            </table>

