name: Deploy my-other-app

on:
  push:
    branches:
      - main
      - production-my-other-app
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build app
        run: |
          cd packages/my-other-app
          pnpm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cf-switch-test
          directory: packages/my-other-app/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref || github.ref_name }}
      - name: Echo outputs
        run: |
          echo ${{ steps.cloudflare.outputs.id }}
          echo ${{ steps.cloudflare.outputs.url }}
          echo ${{ steps.cloudflare.outputs.environment }}
#      - name: Comment deploy url
#        uses: mshick/add-pr-comment@v2
#        with:
#          message-id: cloudflare-deploy
#          message: |
#            ### <span aria-hidden="true">✅</span> Deploy Preview ready!
#
#            |  Name | Link |
#            |---------------------------------|------------------------|
#            |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
#            |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
#            |<span aria-hidden="true">😎</span> Deploy Preview Url | [${{ steps.cloudflare.outputs.url }}](${{ steps.cloudflare.outputs.url }}) |
#            |<span aria-hidden="true">🌳</span> Environment | ${{ steps.cloudflare.outputs.environment }} |
#            ---
